DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS user_loc;
DROP TABLE IF EXISTS user_dynid;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	id		SERIAL PRIMARY KEY,
	username	TEXT NOT NULL UNIQUE,
	name	TEXT NOT NULL UNIQUE,
	passw	TEXT NOT NULL,
	age		INT NOT NULL,
	email	TEXT NOT NULL,
	registered TIMESTAMP DEFAULT DATE_TRUNC('minute', LOCALTIMESTAMP),
	description	TEXT DEFAULT ''
);


CREATE TABLE user_dynid (
	uid 	int NOT NULL	REFERENCES users(id) ON DELETE CASCADE,
	dynid 	TEXT NOT NULL UNIQUE,
	UNIQUE(uid)
);


CREATE TABLE user_loc (
	id		SERIAL PRIMARY KEY,
	dynid	TEXT NOT NULL	REFERENCES user_dynid(dynid) ON DELETE CASCADE,
	geog	geography(POINT,4326) NOT NULL
);


CREATE TABLE messages (
	id 		SERIAL PRIMARY KEY,
	msg 	TEXT NOT NULL,
	send	INT	REFERENCES users(id) ON DELETE CASCADE,
	recv	INT	REFERENCES users(id) ON DELETE CASCADE,
	seen	BOOLEAN DEFAULT FALSE,
	send_date	TIMESTAMP DEFAULT DATE_TRUNC('minute', LOCALTIMESTAMP)
);
